spring.application.name=chatbot-demo-ollama
server.port=8081

#Disable auto-chat client configuration
spring.ai.chat.client.enabled=false

# Logging configuration
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Ollama Chat Model configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3:latest
spring.ai.ollama.chat.options.temperature=0.7

# Ollama Embedding Model configuration
spring.ai.ollama.embedding.enabled=true  
spring.ai.ollama.embedding.options.model=mxbai-embed-large:latest

#default embedding model for ollama is mxbaise-embed-text [dimension 1024]
#other options are nomic-embed-text:latest [dimension 768], embeddingGemma [dimension 768]

#db configuration for mariaDB
#spring.datasource.url=jdbc:mariadb://localhost:3308/spring_ai
#spring.datasource.username=root
#spring.datasource.password=yashavee
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#spring ai vector store configuration for mariaDB
#spring.ai.vectorstore.mariadb.initialize-schema=true
#spring.ai.vectorstore.mariadb.distance-type=COSINE
#spring.ai.vectorstore.mariadb.dimensions=1024

#db configuration for postgres
spring.datasource.url=jdbc:postgresql://localhost:5434/postgres
spring.datasource.username=postgres
spring.datasource.password=yashavee

#spring ai chat memory configuration
spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

#spring ai vector store configuration for pgvector
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024

#db configuration for postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=yashavee


